### ISSUE TITLE
"Last Occurrence" User Incorrect in Reset Message

### ISSUE THREAD

**Issue by TheConnMan** [theawayteam/since#66]
When resetting a timer, the message reads:
> @User1 reset <timer name>! The last occurrence was <time> ago by @User1

If User2 now resets the timer, the message will read:
> @User2 reset <timer name>! The last occurrence was <time> ago by @User2

User1, not User2, set the last occurrence.

**Comment by Grumblesmith** [comment]
Closed by #67
